name: Apply schema migrations

# 👉 Only run this workflow when a change is made to the main branch
on:
  push:
    branches:
      - main

jobs:
  apply_migrations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v2
      - name: Install dependencies & tooling
        run: |
          bun install
          bun install -g drizzle-orm drizzle-kit pg @libsql/client
      - name: Apply migrations
        run: drizzle-kit push
        env:
          TURSO_CONNECTION_URL: ${{ secrets.TURSO_CONNECTION_URL }}
          TURSO_AUTH_TOKEN: ${{ secrets.TURSO_AUTH_TOKEN }}
